backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "foto"
public_folder: "./foto"

collections:
  - name: "global"
    label: "Impostazioni Globali"
    files:
      - name: "settings"
        label: "Dati Contatto & Social"
        file: "data/global/settings.json"
        fields:
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "phone", widget: "string"}
          - {label: "Indirizzo", name: "address", widget: "string"}

  - name: "pages"
    label: "Pagine"
    files:
      - name: "about"
        label: "Pagina Chi Siamo"
        file: "data/pages/about.json"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Descrizione principale", name: "main_description", widget: "text"}
          - {label: "Testo esperienza", name: "experience_text", widget: "text"}
          
      - name: "contact"
        label: "Pagina Contatti"
        file: "data/pages/contact.json"
        fields:
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Sottotitolo", name: "subtitle", widget: "string"}
          
      - name: "services"
        label: "Pagina Servizi"
        file: "data/pages/services.json"
        fields:
          - label: "Elenco Servizi"
            name: "services_list"
            widget: "list"
            fields:
              - {label: "Titolo Servizio", name: "title", widget: "string"}
              - {label: "Descrizione", name: "description", widget: "text"}
              
      - name: "certifications"
        label: "Pagina Certificazioni"
        file: "data/pages/certifications.json"
        fields:
          - label: "Elenco Certificazioni"
            name: "cert_list"
            widget: "list"
            fields:
              - {label: "Titolo Certificazione", name: "title", widget: "string"}
              - {label: "Immagine (WebP preferito)", name: "image", widget: "image"}
  - name: "lavori"
    label: "Lavori"
    files:
      - name: "lavori_file"
        label: "Dati Progetti"
        file: "data/lavori.json"
        fields:
          - label: "Progetti"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Titolo Cliente", name: "title", widget: "string"}
              - {label: "Descrizione Lavoro", name: "description", widget: "text"}
              - {label: "Luogo (Città, Provincia)", name: "location", widget: "string"}
              - {label: "Stato", name: "status", widget: "select", options: ["In Corso", "Terminati 2026", "Terminati 2025", "Terminati 2024", "Terminati 2023"]}

  - name: "carousel"
    label: "Foto Carosello"
    files:
      - name: "carousel_file"
        label: "Dati Carosello"
        file: "data/carousel.json"
        fields:
          - label: "Immagini Carosello"
            name: "images"
            widget: "list"
            field: {label: "Immagine", name: "image", widget: "image"}